fix(rn-reanimated): update SWC config so it won’t add unnecessary helper functions and break react-native-reanimated
Error: [Reanimated] Tried to synchronously call a non-worklet function `_to_consumable_array` on the UI thread.

`target` is removed from SWC config because `env` and `jsc.target` cannot be used together. As a replacement, we use `env.targets`.